import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatSnackBar } from '@angular/material/snack-bar';

import { ApiService } from '../../core/services/api.service';
import { AuthService } from '../../core/services/auth.service';
import { CurrentUserService } from '../../core/services/current-user.service';

@Component({
  selector: 'app-reports-list',
  standalone: true,
  imports: [
    CommonModule, DatePipe, FormsModule,
    MatButtonModule, MatIconModule, MatDialogModule, MatProgressBarModule,
  ],
  template: `
    <div class="page">
      <div class="hdr">
        <div>
          <h1>Reports</h1>
          <p class="muted">Generated incident, capacity and SLA reports</p>
        </div>
        @if (auth.hasRole('ADMIN','MANAGER','AUDITOR')) {
          <button mat-flat-button color="primary" (click)="openCreate()">
            <mat-icon>add</mat-icon> Generate report
          </button>
        }
      </div>

      <div class="panel">
        @if (loading()) { <mat-progress-bar mode="indeterminate" /> }
        <table class="dt">
          <thead>
            <tr><th>ID</th><th>Type</th><th>Parameters</th><th>Generated by</th><th>Generated</th><th>File</th></tr>
          </thead>
          <tbody>
            @for (r of rows(); track r.reportId) {
              <tr>
                <td>{{ r.reportId }}</td>
                <td><span class="pill">{{ r.type }}</span></td>
                <td>{{ r.parametersJson }}</td>
                <td>{{ r.generatedByName || '—' }}</td>
                <td class="muted">{{ r.generatedAt | date:'short' }}</td>
                <td><a [href]="r.reportUri">{{ r.reportUri }}</a></td>
              </tr>
            } @empty {
              <tr><td colspan="6" class="empty">No reports yet.</td></tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  `,
  styles: `
    .page { padding: 20px 24px; max-width: 1400px; margin: 0 auto; }
    .hdr { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 16px; }
    .hdr h1 { font-size: 20px; font-weight: 600; margin: 0; }
    .hdr p { font-size: 12px; color: var(--text-muted); margin: 2px 0 0; }
    .muted { color: var(--text-muted); }
    .panel { background: #fff; border: 1px solid var(--border-soft); border-radius: 8px; overflow: hidden; }
    .dt { width: 100%; border-collapse: collapse; font-size: 12.5px; }
    .dt th, .dt td { padding: 9px 14px; text-align: left; border-bottom: 1px solid var(--border-soft); white-space: nowrap; }
    .dt th { font-size: 10.5px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em;
             color: var(--text-muted); background: #fafbfc; }
    .dt tbody tr:hover { background: rgba(15,23,42,.02); }
    .empty { text-align: center; padding: 32px; color: var(--text-faint); }
    .pill { font-size: 10px; font-weight: 600; padding: 2px 7px; border-radius: 4px;
            letter-spacing: 0.03em; text-transform: uppercase;
            background: var(--brand-50); color: var(--brand-700); }
  `,
})
export class ReportsListComponent implements OnInit {
  protected auth = inject(AuthService);
  private api = inject(ApiService);
  private dialog = inject(MatDialog);
  private currentUser = inject(CurrentUserService);
  private snack = inject(MatSnackBar);

  rows = signal<any[]>([]);
  loading = signal(true);

  ngOnInit() {
    this.currentUser.resolveId().subscribe();
    this.refresh();
  }

  refresh() {
    this.loading.set(true);
    this.api.reports().subscribe({
      next: (r) => { this.rows.set(r); this.loading.set(false); },
      error: () => this.loading.set(false),
    });
  }

  openCreate() {
    const ref = this.dialog.open(ReportFormDialog, { width: '420px' });
    ref.afterClosed().subscribe((ok) => {
      if (ok) { this.snack.open('Report generated', 'OK', { duration: 2500 }); this.refresh(); }
    });
  }
}

@Component({
  selector: 'app-report-form-dialog',
  standalone: true,
  imports: [CommonModule, FormsModule, MatDialogModule, MatFormFieldModule, MatInputModule, MatSelectModule, MatButtonModule],
  template: `
    <h2 mat-dialog-title>Generate report</h2>
    <form #f="ngForm" (ngSubmit)="submit()">
      <mat-dialog-content class="col">
        <mat-form-field appearance="outline">
          <mat-label>Report type</mat-label>
          <mat-select name="type" [(ngModel)]="model.type" required>
            <mat-option value="INCIDENT">Incident report</mat-option>
            <mat-option value="CAPACITY">Capacity report</mat-option>
            <mat-option value="SLA">SLA compliance report</mat-option>
          </mat-select>
          <mat-hint>{{ typeDescription() }}</mat-hint>
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Time window</mat-label>
          <mat-select name="window" [(ngModel)]="model.window" required>
            <mat-option value="7d">Last 7 days</mat-option>
            <mat-option value="30d">Last 30 days</mat-option>
            <mat-option value="90d">Last 90 days</mat-option>
            <mat-option value="1y">Last 12 months</mat-option>
            <mat-option value="all">All time</mat-option>
          </mat-select>
        </mat-form-field>

        @if (model.type === 'INCIDENT') {
          <mat-form-field appearance="outline">
            <mat-label>Filter by severity (optional)</mat-label>
            <mat-select name="severity" [(ngModel)]="model.severity">
              <mat-option [value]="null">All severities</mat-option>
              <mat-option value="CRITICAL">Critical only</mat-option>
              <mat-option value="HIGH">High &amp; above</mat-option>
              <mat-option value="MEDIUM">Medium &amp; above</mat-option>
            </mat-select>
          </mat-form-field>
        }

        @if (model.type === 'SLA') {
          <mat-form-field appearance="outline">
            <mat-label>Filter by priority (optional)</mat-label>
            <mat-select name="priority" [(ngModel)]="model.priority">
              <mat-option [value]="null">All priorities</mat-option>
              <mat-option value="P1">P1 only</mat-option>
              <mat-option value="P2">P2 &amp; above</mat-option>
            </mat-select>
          </mat-form-field>
        }

        <mat-form-field appearance="outline">
          <mat-label>Title (optional)</mat-label>
          <input matInput name="title" [(ngModel)]="model.title"
                 placeholder="e.g. Q4 incident summary">
          <mat-hint>Used as the filename if you don't provide a custom path</mat-hint>
        </mat-form-field>
      </mat-dialog-content>
      <mat-dialog-actions align="end">
        <button mat-button mat-dialog-close type="button">Cancel</button>
        <button mat-flat-button color="primary" type="submit" [disabled]="!f.form.valid">Generate</button>
      </mat-dialog-actions>
    </form>
  `,
  styles: `
    .col { display: flex; flex-direction: column; gap: 4px; padding-top: 12px !important; }
  `,
})
export class ReportFormDialog {
  private api = inject(ApiService);
  private snack = inject(MatSnackBar);
  private ref = inject(MatDialogRef<ReportFormDialog>);
  private currentUser = inject(CurrentUserService);

  model: any = {
    type: 'INCIDENT',
    window: '30d',
    severity: null,
    priority: null,
    title: '',
  };

  typeDescription(): string {
    switch (this.model.type) {
      case 'INCIDENT': return 'Open / resolved fault counts, MTTR, top sites by incidents';
      case 'CAPACITY': return 'Plans, approvals, measured throughput vs target';
      case 'SLA':      return 'Tickets that breached or met SLA windows';
      default:         return '';
    }
  }

  submit() {
    const id = this.currentUser.userId();
    if (!id) { this.snack.open('User id not resolved', 'OK', { duration: 3000 }); return; }

    // Build the parametersJson string from the friendly form fields.
    const params: Record<string, string> = { window: this.model.window };
    if (this.model.severity) params['severity'] = this.model.severity;
    if (this.model.priority) params['priority'] = this.model.priority;
    if (this.model.title)    params['title']    = this.model.title;

    // Auto-build a reportUri from type + window if user didn't provide a title.
    const safeTitle = (this.model.title || `${this.model.type.toLowerCase()}-${this.model.window}`)
                        .toLowerCase().replace(/[^a-z0-9]+/g, '-');
    const reportUri = `/reports/${safeTitle}-${Date.now()}.pdf`;

    this.api.generateReport({
      type: this.model.type,
      parametersJson: JSON.stringify(params),
      reportUri,
      generatedBy: id,
    }).subscribe({
      next: () => this.ref.close(true),
      error: (err: any) => this.snack.open(err?.error?.message ?? 'Generation failed', 'OK', { duration: 4000 }),
    });
  }
}
