package com.project.netops.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class ReportRequest {
    @NotBlank(message = "Report type is required") private String type;
    private String parametersJson;
    @NotNull(message = "Generated by is required") private Integer generatedBy;
    private String reportUri;
}
